version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
#    command: sh -c "composer install"
volumes:
  db_data: {}